/*
  Seed the services CMS with the catalog that predates the database-backed CMS.

  The original migration created an empty table. The client then used static
  fallback data only while the table had zero rows, so the first CMS insert
  caused the public catalog to collapse from ten services to one. Preserve any
  service already customized by an administrator and fill only missing slugs.
*/

INSERT INTO public.company_services (
  title,
  title_ar,
  short_description,
  short_description_ar,
  description,
  description_ar,
  slug,
  icon,
  color,
  category,
  category_ar,
  benefits,
  benefits_ar,
  process,
  process_ar,
  ecosystem_angle,
  show_on_homepage,
  is_published,
  display_order
)
VALUES
  ('Web Development',
   'تطوير المواقع الإلكترونية',
   'High-performance web applications built with modern stacks.',
   'تطبيقات ويب عالية الأداء بأحدث التقنيات.',
   'High-performance web applications engineered for scale. From marketing websites to complex enterprise platforms — built with modern stacks and optimized for conversion.',
   'تطبيقات ويب عالية الأداء مبنية للتوسع. من مواقع التسويق إلى منصات المؤسسات المعقدة — بأحدث التقنيات ومُحسَّنة للتحويل.',
   'web-development',
   'Globe',
   '#3b82f6',
   'Technology',
   'التقنية',
   '["Lightning-fast load times (< 2s)","Mobile-first responsive design","SEO-optimized architecture","CMS integration","Custom dashboards & admin panels"]'::jsonb,
   '["أوقات تحميل فائقة السرعة (أقل من ثانيتين)","تصميم متجاوب يُقدّم الجوال أولاً","بنية محسّنة لمحركات البحث","تكامل مع أنظمة إدارة المحتوى","لوحات تحكم وأنظمة إدارية مخصصة"]'::jsonb,
   '["Discovery & Requirements","Architecture Design","Development Sprint","QA & Testing","Launch & Monitoring"]'::jsonb,
   '["الاستكشاف وتحديد المتطلبات","تصميم البنية التقنية","دورة التطوير","ضمان الجودة والاختبار","الإطلاق والمراقبة"]'::jsonb,
   0,
   true,
   true,
   0),
  ('Mobile App Development',
   'تطوير تطبيقات الجوال',
   'Native and cross-platform mobile applications for iOS & Android.',
   'تطبيقات الجوال الأصلية ومتعددة المنصات.',
   'Native iOS and Android applications, as well as cross-platform solutions using React Native. Deliver seamless experiences that users love and businesses depend on.',
   'تطبيقات iOS و Android الأصلية وكذلك الحلول متعددة المنصات باستخدام React Native. نقدم تجارب سلسة يحبها المستخدمون وتعتمد عليها الأعمال.',
   'mobile-app-development',
   'Smartphone',
   '#10b981',
   'Technology',
   'التقنية',
   '["iOS & Android coverage","Offline functionality","Push notifications","App Store optimization","Analytics integration"]'::jsonb,
   '["تغطية iOS و Android","وظائف بدون اتصال","إشعارات فورية","تحسين متاجر التطبيقات","تكامل التحليلات"]'::jsonb,
   '["UX Research","Prototype & Design","Development","Beta Testing","App Store Submission"]'::jsonb,
   '["أبحاث تجربة المستخدم","النموذج الأولي والتصميم","التطوير","اختبار النسخة التجريبية","نشر التطبيق"]'::jsonb,
   36,
   true,
   true,
   1),
  ('Systems Development & Automation',
   'تطوير الأنظمة والأتمتة',
   'Custom ERP, CRM, and workflow automation systems.',
   'أنظمة ERP وCRM وأتمتة سير العمل.',
   'Custom ERP, CRM, and workflow automation systems that eliminate manual processes and unlock operational efficiency at scale.',
   'أنظمة ERP و CRM وأتمتة سير العمل المخصصة التي تقضي على العمليات اليدوية وتُطلق الكفاءة التشغيلية على نطاق واسع.',
   'systems-automation',
   'Settings',
   '#f5a623',
   'Technology',
   'التقنية',
   '["Workflow automation","ERP/CRM customization","API integrations","Real-time dashboards","Role-based access control"]'::jsonb,
   '["أتمتة سير العمل","تخصيص ERP/CRM","تكاملات API","لوحات بيانات فورية","التحكم في الوصول بالصلاحيات"]'::jsonb,
   '["Process Audit","System Design","Development","User Training","Continuous Optimization"]'::jsonb,
   '["تدقيق العمليات","تصميم النظام","التطوير","تدريب المستخدمين","التحسين المستمر"]'::jsonb,
   72,
   true,
   true,
   2),
  ('UI/UX Design',
   'تصميم تجربة وواجهة المستخدم',
   'Research-driven design systems that convert visitors into customers.',
   'أنظمة تصميم تحوّل الزوار إلى عملاء.',
   'Research-driven design that converts. We create design systems and user experiences that reduce friction, increase trust, and drive measurable business results.',
   'تصميم مدفوع بالأبحاث يُحوّل الزوار إلى عملاء. نبني أنظمة تصميم وتجارب مستخدم تقلل الاحتكاك وتزيد الثقة وتحقق نتائج أعمال قابلة للقياس.',
   'ui-ux-design',
   'Palette',
   '#ec4899',
   'Design',
   'التصميم',
   '["User research & testing","Design system creation","Conversion optimization","Accessibility compliance","Interactive prototypes"]'::jsonb,
   '["أبحاث واختبار المستخدمين","إنشاء نظام تصميم","تحسين التحويل","الامتثال لمعايير إمكانية الوصول","نماذج أولية تفاعلية"]'::jsonb,
   '["User Research","Information Architecture","Wireframing","Visual Design","Usability Testing"]'::jsonb,
   '["بحث المستخدمين","هندسة المعلومات","الإطارات السلكية","التصميم البصري","اختبار قابلية الاستخدام"]'::jsonb,
   108,
   true,
   true,
   3),
  ('Business Development & Restructuring',
   'تطوير الأعمال وإعادة الهيكلة',
   'Strategic restructuring and business transformation services.',
   'إعادة الهيكلة والتحول التجاري الاستراتيجي.',
   'Strategic business transformation from the ground up. We analyze, restructure, and rebuild operations for sustainable competitive advantage.',
   'تحول استراتيجي شامل للأعمال من الأساس. نحلل ونُعيد الهيكلة ونُعيد بناء العمليات لميزة تنافسية مستدامة.',
   'business-development',
   'TrendingUp',
   '#8b5cf6',
   'Business',
   'الأعمال',
   '["Market entry strategy","Operational restructuring","Revenue model optimization","Competitive analysis","KPI framework design"]'::jsonb,
   '["استراتيجية دخول السوق","إعادة الهيكلة التشغيلية","تحسين نموذج الإيرادات","التحليل التنافسي","تصميم إطار KPI"]'::jsonb,
   '["Business Audit","Gap Analysis","Strategy Development","Implementation","Performance Tracking"]'::jsonb,
   '["تدقيق الأعمال","تحليل الفجوات","تطوير الاستراتيجية","التنفيذ","تتبع الأداء"]'::jsonb,
   144,
   true,
   true,
   4),
  ('Payment Gateway Integration',
   'تكامل بوابات الدفع',
   'Seamless payment gateways: Mada, Tabby, Tamara, Stripe.',
   'بوابات دفع متكاملة: مدى، تابي، تمارا، سترايب.',
   'Seamless, secure payment processing integrated into your platforms. We support all major Saudi and international payment gateways.',
   'معالجة مدفوعات سلسة وآمنة مدمجة في منصاتك. ندعم جميع بوابات الدفع السعودية والدولية الرئيسية.',
   'payment-integration',
   'CreditCard',
   '#14b8a6',
   'Technology',
   'التقنية',
   '["Mada, Tabby, Tamara","Stripe & PayPal","Apple Pay & Google Pay","STC Pay & Urpay","PCI DSS compliant"]'::jsonb,
   '["مدى، تابي، تمارا","Stripe و PayPal","Apple Pay و Google Pay","STC Pay و Urpay","متوافق مع PCI DSS"]'::jsonb,
   '["Gateway Selection","API Integration","Security Testing","Checkout Optimization","Monitoring Setup"]'::jsonb,
   '["اختيار بوابة الدفع","تكامل API","اختبار الأمان","تحسين الدفع","إعداد المراقبة"]'::jsonb,
   180,
   true,
   true,
   5),
  ('Full Business Consulting',
   'الاستشارات التجارية الشاملة',
   'End-to-end business setup from legal structure to market entry.',
   'تأسيس الأعمال من الهيكل القانوني إلى دخول السوق.',
   'End-to-end business establishment — from legal entity setup to market strategy and brand positioning. We build businesses from concept to launch.',
   'إنشاء أعمال شامل من الألف إلى الياء — من التأسيس القانوني إلى استراتيجية السوق وتموضع العلامة التجارية. نبني الأعمال من الفكرة إلى الإطلاق.',
   'business-consulting',
   'Briefcase',
   '#f59e0b',
   'Business',
   'الأعمال',
   '["Commercial registration","Business plan development","Brand strategy","Financial modeling","Market entry consulting"]'::jsonb,
   '["التسجيل التجاري","تطوير خطة الأعمال","استراتيجية العلامة التجارية","النمذجة المالية","استشارات دخول السوق"]'::jsonb,
   '["Concept Validation","Business Planning","Legal Setup","Brand Development","Market Launch"]'::jsonb,
   '["التحقق من الفكرة","التخطيط التجاري","الإعداد القانوني","تطوير العلامة","الإطلاق في السوق"]'::jsonb,
   216,
   true,
   true,
   6),
  ('E-commerce Store Setup (Salla)',
   'إعداد متاجر إلكترونية على سلة',
   'Full Salla store setup with custom themes and optimization.',
   'إعداد متجر سلة كامل بقوالب مخصصة.',
   'Complete Salla e-commerce store setup with custom themes, product catalog management, payment integration, and conversion optimization.',
   'إعداد متجر سلة الإلكتروني بالكامل مع قوالب مخصصة وإدارة كتالوج المنتجات وتكامل الدفع وتحسين التحويل.',
   'ecommerce-salla',
   'ShoppingBag',
   '#06b6d4',
   'E-commerce',
   'التجارة الإلكترونية',
   '["Custom Salla theme design","Product catalog setup","Payment gateway activation","Shipping configuration","SEO & marketing setup"]'::jsonb,
   '["تصميم قالب سلة مخصص","إعداد كتالوج المنتجات","تفعيل بوابة الدفع","إعداد الشحن","إعداد SEO والتسويق"]'::jsonb,
   '["Store Planning","Theme Customization","Product Import","Payment Setup","Launch & Training"]'::jsonb,
   '["تخطيط المتجر","تخصيص القالب","استيراد المنتجات","إعداد الدفع","الإطلاق والتدريب"]'::jsonb,
   252,
   true,
   true,
   7),
  ('SEO Optimization',
   'تحسين محركات البحث',
   'Technical and content SEO that dominates Google rankings.',
   'SEO تقني ومحتوى يتصدر نتائج جوجل.',
   'Technical and content SEO strategies that drive sustainable organic growth. Dominate search rankings in your target market — Arabic and English.',
   'استراتيجيات SEO تقنية ومحتوى تدفع النمو العضوي المستدام. احتلّ صدارة نتائج البحث في سوقك المستهدف — بالعربية والإنجليزية.',
   'seo-optimization',
   'Search',
   '#84cc16',
   'Marketing',
   'التسويق',
   '["Technical SEO audit","Keyword strategy","Content optimization","Link building","Local SEO for Saudi market"]'::jsonb,
   '["تدقيق SEO التقني","استراتيجية الكلمات المفتاحية","تحسين المحتوى","بناء الروابط","SEO المحلي للسوق السعودي"]'::jsonb,
   '["SEO Audit","Keyword Research","On-Page Optimization","Content Strategy","Reporting & Refinement"]'::jsonb,
   '["تدقيق SEO","بحث الكلمات المفتاحية","تحسين الصفحات","استراتيجية المحتوى","التقارير والتحسين"]'::jsonb,
   288,
   true,
   true,
   8),
  ('AI Solutions',
   'حلول الذكاء الاصطناعي',
   'Custom AI integrations, chatbots, and machine learning systems.',
   'تكاملات الذكاء الاصطناعي والروبوتات وأنظمة التعلم الآلي.',
   'Custom AI integrations that give your business a competitive edge. Intelligent chatbots, automation workflows, and machine learning systems tailored to your needs.',
   'تكاملات ذكاء اصطناعي مخصصة تمنح أعمالك ميزة تنافسية. روبوتات محادثة ذكية وتدفقات أتمتة وأنظمة تعلم آلي مصممة لاحتياجاتك.',
   'ai-solutions',
   'Brain',
   '#f43f5e',
   'AI & Innovation',
   'الذكاء الاصطناعي والابتكار',
   '["AI chatbot development","Process automation with AI","Data analytics & insights","Predictive modeling","LLM integration (GPT, Gemini)"]'::jsonb,
   '["تطوير روبوتات المحادثة","أتمتة العمليات بالذكاء الاصطناعي","تحليل البيانات والرؤى","النمذجة التنبؤية","تكامل نماذج اللغة الكبيرة (GPT، Gemini)"]'::jsonb,
   '["AI Readiness Assessment","Use Case Definition","Model Selection","Integration & Training","Monitoring & Refinement"]'::jsonb,
   '["تقييم الجاهزية للذكاء الاصطناعي","تحديد حالات الاستخدام","اختيار النموذج","التكامل والتدريب","المراقبة والتحسين"]'::jsonb,
   324,
   true,
   true,
   9)
ON CONFLICT (slug) DO NOTHING;
